name: 'Set JSON'
description: 'Updates a key value pair of a file'
inputs:
  file:
    description: 'JSON file to update'
    required: true
    default: 'test.json'
  key:
    description: 'Key to set'
    required: true
    default: 'test'
  value:
    description: 'Value to set'
    required: true
    default: 'value'
outputs:
  obj:
    description: 'JSON object after modification'
runs:
  using: 'node12'
  main: 'index.js'
